# Inputs CloudSaw supplies on every plan/apply.
#
# The Rust caller (terraform::runner) writes these into a `tfvars.auto.tfvars.json`
# file in the per-account working directory. The values are never user-typed:
#   * trusted_principal_arn is the result of sts:GetCallerIdentity at provisioning
#     time, with assumed-role sessions unwrapped to the underlying role ARN.
#   * policy_variant is one of {"security_audit", "read_only_access"} and maps
#     to AWS-managed-policy ARNs below. SecurityAudit is the default per
#     Contract 05 §Constraints; ReadOnlyAccess is an explicit opt-in.
#   * external_id is a CloudSaw-generated per-account random string (kept in
#     SQLite, NEVER a credential — it's just a confused-deputy guard tied to
#     the trust policy so a stolen role ARN alone can't be assumed).
#   * role_name is a constant ("CloudSawScannerRole") but exposed as a variable
#     so tests / future contracts can drive it.

variable "role_name" {
  description = "Name of the IAM role CloudSaw creates."
  type        = string
  default     = "CloudSawScannerRole"

  validation {
    condition     = can(regex("^[A-Za-z0-9+=,.@_-]{1,64}$", var.role_name))
    error_message = "role_name must match the IAM role-name grammar (1-64 chars, [A-Za-z0-9+=,.@_-])."
  }
}

variable "trusted_principal_arn" {
  description = "ARN allowed to assume the scanner role. Set by CloudSaw to the underlying caller ARN — never a wildcard, never user-typed."
  type        = string

  validation {
    condition = (
      can(regex("^arn:aws:iam::[0-9]{12}:role/.+$", var.trusted_principal_arn)) ||
      can(regex("^arn:aws:iam::[0-9]{12}:user/.+$", var.trusted_principal_arn)) ||
      can(regex("^arn:aws:iam::[0-9]{12}:root$", var.trusted_principal_arn))
    )
    error_message = "trusted_principal_arn must be an IAM role/user/root ARN. Wildcards and STS session ARNs are not permitted."
  }
}

variable "policy_variant" {
  description = "Which AWS-managed scanner policy to attach. Default 'security_audit'; 'read_only_access' is an opt-in with broader read access."
  type        = string
  default     = "security_audit"

  validation {
    condition     = contains(["security_audit", "read_only_access"], var.policy_variant)
    error_message = "policy_variant must be 'security_audit' or 'read_only_access'."
  }
}

variable "external_id" {
  description = "Random per-account string included in the trust policy as a confused-deputy guard. Generated by CloudSaw, stored locally."
  type        = string

  validation {
    condition     = length(var.external_id) >= 16 && length(var.external_id) <= 1224
    error_message = "external_id must be 16-1224 characters (AWS sts:ExternalId limits)."
  }
}
